on:
  workflow_dispatch:
name: Deploy Azure Resources
permissions:
  id-token: write
  contents: read
jobs:
  deploy-and-configure-azure:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

      # Deploy Bicep templates
    # - name: Deploy Resources
    #   id: deploy
    #   uses: azure/arm-deploy@v2
    #   with:
    #     scope: 'subscription'
    #     region: 'UK South'
    #     resourceGroupName: ${{ secrets.AZURE_RG }}
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     parameters: 'resourceGroupName=${{ secrets.AZURE_RG }} sqlAdmins=${{ secrets.SQL_ADMINS }}'
    #     template: ./main.bicep
      
      # Grant SQL Server Directory Readers Role
      ####### !!!! THIS NEEDS A GROUP ALREADY EXISTING NAMED 'Directory Readers' WITH THAT ROLE BC MICROSOFT ARE A CHORE AND I CANT BE BOTHERED TO AUTOMATE THIS CRAPULENCE AFTER TRYING 5 DIFFERENT WAYS
    - name: Grant SQL Entra Role
      id: sqlentrarole
      uses: azure/powershell@v2
      with:
        inlineScript: |
          ./powershellscripts/entraacl.ps1 ${{ secrets.SQL_NAME }}
        azPSVersion: latest

      # Grant Web App to SQL access using SQL script
    # - name: Grant Web App SQL Access
    #   id: sqlconnection
    #   uses: azure/sql-action@v2.3
    #   with:        
    #     connection-string: 'Server=${{ steps.deploy.outputs.sqlServerName }}.database.windows.net;Initial Catalog=${{ steps.deploy.outputs.sqlDatabaseName }};Authentication=Active Directory Default; Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    #     arguments: '-v webSiteName="${{ steps.deploy.outputs.webSiteName }}"'
    #     path: './sqlscripts/acl.sql'