on:
  workflow_dispatch:
name: Deploy Entra Event Handler
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy ARM templates
    - name: Deploy Resources
      id: deploy
      uses: azure/arm-deploy@v2
      with:
        scope: 'subscription'
        region: 'UK South'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./main.bicep